import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import {
  AppBar,
  Box,
  CardMedia,
  Stack,
  Toolbar,
  Typography,
} from "@mui/material";
import Navbar from "./components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Soft dev</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
        />
      </Head>
      <main>
        <Stack direction="column" alignItems="center">
          <Box pt={10} textAlign="center">
            <Typography variant="h5" fontFamily="Merriweather" my={5}>
              Welcome to Soft Dev
            </Typography>
            <CardMedia
              component="img"
              image="https://cdn.pixabay.com/photo/2015/09/09/19/56/office-932926__340.jpg"
              alt="home-image"
              sx={{
                height: {
                  xs: "300px",
                  sm: "500px",
                },
                width: "100%",
                maxWidth: "600px",
              }}
            />
          </Box>
        </Stack>
      </main>
    </>
  );
}
